### ISSUE TITLE
anamorphic videos are not displayed correctly

### ISSUE THREAD

**Issue by bennettpeter** [android/tv-samples#10]
I am playing a 720x480 video that is supposed to be shown at 16x9. It is showing vertically compressed as if it used square pixels. I added a VideoListener with onVideoSizeChanged method. That method is called with the correct values of 720 480 1.1851852. A strange thing is that if I set a breakpoint in that method, when it hits the breakpoint during start of play, the video is showing and playing at the correct shape, but as soon as that method is allowed to continue, the video shifts to the wrong size.

**Comment by bennettpeter** [comment]
I found that this is a bug in the Exoplayer leanback extension. I have submitted a pull request to fix it. 
see https://github.com/google/ExoPlayer/pull/6578

**Comment by IanGClifton** [comment]
Thanks for submitting the PR to fix this in the ExoPlayer repository. It looks like that's merged in, so is it safe to close out this bug?

**Comment by bennettpeter** [comment]
Closing as this has been fixed and merged.
