### ISSUE TITLE
Immersive list doesn't scroll to the top of the screen when expending

### ISSUE THREAD

**Issue by DriesDingenen** [android/tv-samples#112]
[JetStreams]

When utilizing the immersive list component on Android TV, the row expands upon selection. However, it fails to scroll to the top of the screen, resulting in the ImmersiveListScope occupying only half of the screen.

![immersive_list_bug](https://github.com/android/tv-samples/assets/133032726/318ede9c-1583-40f2-ab8e-9073d6712435)

**Comment by DriesDingenen** [comment]
https://issuetracker.google.com/issues/256678892

**Comment by vighnesh153** [comment]
Thanks for the comment. This is a known issue and happens when it gains focus. If you go to previous or next item, it does move to the top of the screen.
