### ISSUE TITLE
JetStreamCompose Sample Project - Details Screen Does Not Show Selected Movie

### ISSUE THREAD

**Issue by androiddeveloperfl** [android/tv-samples#113]
I'm running an un-modified copy of the Official 'Jetpack Compose for TVSamples' project - and I'm trying to figure out why the *'MovieDetailsScreen.kt'* never successfully displays the movie clicked on / selected in *'HomeScreen.kt'*. 

**Official Google Source code** (with the bug in it):

https://github.com/android/tv-samples/tree/main/JetStreamCompose

Long story short: No matter which movie is selected:

[![enter image description here][1]][1]

 ...the 'details screen' always displays the same movie (which isn't the one clicked): 

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/kGtbH.jpg
  [2]: https://i.stack.imgur.com/yRoE8.jpg

Any suggestions / tips are appreciated.

**Comment by vighnesh153** [comment]
Thanks for reporting. We will investigate this and get back.
