### ISSUE TITLE
JetStreamCompose Sample project doesn't have navigation drawer example

### ISSUE THREAD

**Issue by rahulpandey** [android/tv-samples#115]

**Comment by vighnesh153** [comment]
Thanks for reporting. Until we add, could you check the samples on [cs.android.com/androidx/platform/frameworks/support](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:tv/) and let me know if that helps? Look at `tv/tv-samples` and `tv/integration-tests/playground`

**Comment by rahulpandey** [comment]
Thanks . This is what I was look for.
