### ISSUE TITLE
TvLazyRow/TvLazyColumn scrolling issue

### ISSUE THREAD

**Issue by dogancankilic** [android/tv-samples#118]
https://github.com/android/tv-samples/assets/43243372/fe1d34ed-6f94-46f9-ba0d-42ffefff2cff

Upon scrolling horizontally using TvLazyRow or vertically using TvLazyColumn, the items won’t snap into place immediately. There’s always an animation before snapping the items into place. This animation shows itself as a jumping action or a laggy behavior. Is there a way to deactivate this animation? Or, can the animation and snapping of items into place occur smoothly?

**Comment by vighnesh153** [comment]
IssueTracker bug: https://issuetracker.google.com/issues/285746919

**Comment by chikoski** [comment]
@dogancankilic I believe the animation performance is improved with the latest commit, and it shows less laggy behavior. Let me close this issue for now. Feel free to re-open when you find the screen shows laggy behavior.
