### ISSUE TITLE
How to enable system sounds with Jetpack Compose for Android TV?

### ISSUE THREAD

**Issue by kerimbr** [android/tv-samples#125]
Hello,

I'm developing an application for Android TV using Jetpack Compose. Within my application, I want to produce system sounds when navigating through a list or during navigations. For instance, I want a sound to be made when an item is focused or clicked on.

Is there a recommended way to produce any sound? Can I get information about using Android's built-in sound effects and how to integrate these sound effects into Jetpack Compose UI interactions?

Any help is appreciated. Thank you!

**Comment by vighnesh153** [comment]
Let me know if this answers your question: https://stackoverflow.com/a/76796468/8822610
