### ISSUE TITLE
Baseline Profile is broken in JetStream (Compose)

### ISSUE THREAD

**Issue by guerdaa** [android/tv-samples#128]
I started the baseline profile on an emulator (Android TV 1080p API 34) and as soon as the test starts, the app opens at the beginning and then moves to the background and the actions are performed on the menu screen of the emulator (the app stays in the background).

**Comment by chikoski** [comment]
Thanks for reporting this! Let me take a look.

**Comment by sushantshirekar** [comment]
Is this issue solved ? 
@chikoski
