### ISSUE TITLE
Documentsui for Google tvs

### ISSUE THREAD

**Issue by Joubitor** [android/tv-samples#130]
Is possible to make the documents ui works in Android tv 11?

**Comment by vighnesh153** [comment]
What is your usecase?

**Comment by Handrail9** [comment]
> What is your usecase?
> 
> Unfortunately, the DocumentsUI module is not available on Android TV.

Dont know about OP but my usecase is I'd like to launch apps with documentsui intents such as KDE connect to send pictures and have them save to pictures instead of Downloads.
