### ISSUE TITLE
Multiple Searchable Activities.

### ISSUE THREAD

**Issue by MrJorgeXavier** [android/tv-samples#14]
Is there a way to have multiple entrypoints for the Global Search intent? I have an activity specific for handle search just like in the documentation, regardless of the path pattern in the searched content.
I would like to have activities able to handle search according to the path pattern in the data of the search intent, just like i do with Channels for example.
Here is an example of what I mean:
```xml
<activity android:name=".videos.EpisodeActivity">
            <intent-filter>
                <action android:name="android.intent.action.SEARCH" />

                <data
                    android:host="*"
                    android:pathPattern=".*/episode/.*"
                    android:scheme="${app_scheme}" />
            </intent-filter>

            <meta-data
                android:name="android.app.searchable"
                android:resource="@xml/searchable" />
</activity>

<activity android:name=".movies.MovieActivity">
            <intent-filter>
                <action android:name="android.intent.action.SEARCH" />

                <data
                    android:host="*"
                    android:pathPattern=".*/movie/.*"
                    android:scheme="${app_scheme}" />
            </intent-filter>

            <meta-data
                android:name="android.app.searchable"
                android:resource="@xml/searchable" />
</activity>
```
However, if i specify a ```<data>``` inside of the intent-filter like described above, the global search just stops working.

Is there a way to do this?

**Comment by IanGClifton** [comment]
I'm not sure if that's supported by the framework. It might be worth asking at StackOverflow since it's more of a general Android question (not specific to this repo or Android TV).
