### ISSUE TITLE
Unable to clone tv-sample repo

### ISSUE THREAD

**Issue by IamYou2** [android/tv-samples#147]
git clone https://developer.android.com/jetpack/androidx/releases/tv
Cloning into 'tv'...
fatal: unable to update url base from redirection:
  asked for: https://developer.android.com/jetpack/androidx/releases/tv/info/refs?service=git-upload-pack
   redirect: https://developer.android.com/jetpack/androidx/versions?service=git-upload-pack

**Comment by chikoski** [comment]
Thanks for reporting and you look cloning the repository from incorrect URL. 

I believe we can clone the sample apps from this URL: https://github.com/android/tv-samples.git
