### ISSUE TITLE
JetStream crashes on home screem : Focus restoration on navigation popBackStack and focus restoration using state Modifiers

### ISSUE THREAD

**Issue by ChetanPatelPlayBoxTV** [android/tv-samples#148]
In the JetStream tv app sample, it has a createInitialFocusRestorerModifiers() function which acts as the focus restorers of a TvLazyRow/Column for its children.

When I tried to scroll to the end item of the list - making the first item hidden from the current view - and tried to go to my second screen and immediately pop back from it, the app constantly throws:

`  java.lang.IllegalStateException: 
FocusRequester is not initialized. Here are some possible fixes:                                                                                                    
1. Remember the FocusRequester: val focusRequester = remember { FocusRequester() }
2. Did you forget to add a Modifier.focusRequester() ?
3. Are you attempting to request focus during composition? Focus requests should be made in
   response to some event. Eg Modifier.clickable { focusRequester.requestFocus() }
   	at androidx.compose.ui.focus.FocusRequester.focus$ui_release(FocusRequester.kt:259)
  	at androidx.compose.ui.focus.FocusTransactionsKt.performCustomEnter-Mxy_nc0(FocusTransactions.kt:293)
   	at androidx.compose.ui.focus.FocusTransactionsKt.performCustomRequestFocus-Mxy_nc0(FocusTransactions.kt:271)`

**Comment by alexzaitsev** [comment]
Have you found a solution @ChetanPatelPlayBoxTV ? Seems to be an issue in `FocusRestorer` modifier.

**Comment by ChetanPatelPlayBoxTV** [comment]
> Have you found a solution @ChetanPatelPlayBoxTV ? Seems to be an issue in `FocusRestorer` modifier.

@alexzaitsev Sorry still I'm facing same issue, it's not  resolved.

**Comment by ChetanPatelPlayBoxTV** [comment]
any update @androidTeam @alexzaitsev @dakkad @tjohns 

How can I solved this issue ?

**Comment by chikoski** [comment]
This issue can be fixed by [this](https://b.corp.google.com/issues/312677265#comment9), which is applied by #168

**Comment by ChetanPatelPlayBoxTV** [comment]
thanks @chikoski  for update me and give me quick solution.

**Comment by chemickypes** [comment]
Where do I have to see the solution? Which files?
