### ISSUE TITLE
Selecting Seekbar to move video time freezes controls

### ISSUE THREAD

**Issue by dgocoder** [android/tv-samples#174]
Seeking on content by selecting bar before would allow you to move throughout video.

Now since this change, it is broken and doing so freezes controls and any action until controls become not visible.

Looks like after this PR was merged: https://github.com/android/tv-samples/pull/168

At commit fc5dcc0ec50da71e188b72fc4ff6ddca39b57402
Seekbar works as expected

https://github.com/android/tv-samples/assets/13984190/99ce79f2-eaa2-4428-8230-8198816f48c2

Post those changes:

https://github.com/android/tv-samples/assets/13984190/4481a986-d54c-4ff2-8796-20d239e9680e

**Comment by dgocoder** [comment]
@chikoski I believe this to be related to the most recent pr change: https://github.com/android/tv-samples/pull/168

**Comment by chikoski** [comment]
@dgocoder Thanks for reporting this issue. This issue could be related to #159.

**Comment by dgocoder** [comment]
At first I thought so but confirmed that did not cause the issue.
