### ISSUE TITLE
Removing tv-foundation and replacing TvLazyRow with LazyRow

### ISSUE THREAD

**Issue by guan1** [android/tv-samples#178]
Hi,

I've a question - in this commit https://github.com/android/tv-samples/commit/dca953ee160ec048eab3dba959797785966c2642
you've removed the tv-foundation dependency and you've replaced TvLazyRow with LazyRow.

We did that in our app as well and noticed a significant performance improvement. But we were wondering, what the reason behind this change is? Is tv-foundation not needed anymore? We couldn't find any information about that in any Google IO session, also the official TV compose documentation still mentions that we should use tv-foundation and TvLazyRow. So what's the right approach here? Can you shed some light why you did those changes?

Thanks in advance and best regards,
Andre

**Comment by chikoski** [comment]
Compose foundation now provides all features available in tv-foundation. Please take a look at [this post](https://medium.com/androiddevelopers/migrating-compose-for-tv-from-alpha-to-stable-b0074d6fd350) for more information.
