### ISSUE TITLE
[BUG] App crashes when trying to focus item on back navigation

### ISSUE THREAD

**Issue by GeorgiBurgazliev** [android/tv-samples#179]
Steps to reproduce:
1. Choose a row (for example Trending)
2. Move the focus so you hide the first item (for example go to "The invisible man")
3. Open details 
4. Navigate back. 

App crashes:
FocusRequester is not initialized.

**Comment by chikoski** [comment]
@GeorgiBurgazliev Is this issue for JetStream? Just in case.

**Comment by chikoski** [comment]
Thanks for reporting this. I could reproduce the issue with the steps.

**Comment by chikoski** [comment]
I believe this issue is fixed with #180.
