### ISSUE TITLE
Alarms Not Triggering After TV Is Turned Off or Restarted

### ISSUE THREAD

**Issue by Jacko760** [android/tv-samples#186]
Hello Community,

I am developing an application for an Android TV that schedules prayer times using AlarmManager. I have tried multiple approaches to ensure that the alarms trigger correctly even when the TV is turned off or restarted. However, I am encountering issues where the alarms do not trigger as expected. Here are the details of my attempts and the current behavior:

Current Implementation:

	1.	AlarmManager with setExact and setAlarmClock:
	•	I have used setExact and setAlarmClock methods of AlarmManager to schedule the alarms.
	•	Alarms work correctly when the TV is on but do not trigger when the TV is turned off or in standby mode.
	2.	Wake Lock:
	•	I have acquired a wake lock to keep the device awake during the alarm trigger.
	•	This also did not resolve the issue when the TV is turned off.
	3.	BroadcastReceiver for BOOT_COMPLETED:
	•	I have implemented a BroadcastReceiver to reschedule alarms when the TV is restarted.
	•	The receiver does not seem to work as expected. It appears that background services are force-killed once the TV is turned off.

	4.	Running MediaPlayer.start as a Service:
	•	I have tried running MediaPlayer.start as a service to ensure that the sound plays even when the TV is in sleep mode.
	•	This approach also did not yield the desired results as the service seems to be stopped when the TV is turned off.

Code Snippets:

BootReceiver.java:

package com.example.azan;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.widget.Toast;

public class BootReceiver extends BroadcastReceiver {
    @Override
    public void onReceive(Context context, Intent intent) {
        if (Intent.ACTION_BOOT_COMPLETED.equals(intent.getAction())) {
            Toast.makeText(context, "Boot Completed, rescheduling alarms", Toast.LENGTH_SHORT).show();
            // Reschedule all your alarms here
            AlarmHelper alarmHelper = new AlarmHelper(context);
            alarmHelper.setNextDayPrayerAlarms();
        }
    }
}

AndroidManifest.xml:

<receiver
    android:name=".BootReceiver"
    android:enabled="true"
    android:exported="false">
    <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED" />
    </intent-filter>
</receiver>
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

Alarm Setting Code:

private void setTestAlarm() {
    AlarmManager alarmManager = (AlarmManager) getSystemService(Context.ALARM_SERVICE);
    Intent intent = new Intent(this, AlarmReceiver.class);
    intent.putExtra("PRAYER_NAME", "Test Alarm");
    intent.putExtra("SOUND_RESOURCE", R.raw.notification_fajr);
    PendingIntent pendingIntent = PendingIntent.getBroadcast(this, "Test Alarm".hashCode(), intent, PendingIntent.FLAG_UPDATE_CURRENT);
    Calendar calendar = Calendar.getInstance();
    calendar.set(Calendar.HOUR_OF_DAY, 14);
    calendar.set(Calendar.MINUTE, 21);
    calendar.set(Calendar.SECOND, 0);
    if (calendar.before(Calendar.getInstance())) {
        calendar.add(Calendar.DAY_OF_MONTH, 1);
    }
    if (alarmManager != null) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            alarmManager.setAlarmClock(new AlarmManager.AlarmClockInfo(calendar.getTimeInMillis(), pendingIntent), pendingIntent);
        }
    }
}

Issues:

	1.	Alarms do not trigger when the TV is turned off or in standby mode.
	2.	The BOOT_COMPLETED broadcast receiver does not seem to work when the TV restarts, possibly due to background services being force-killed.

Questions:

	1.	What is the expected behavior for AlarmManager and BOOT_COMPLETED broadcast receivers on Android TV when the device is turned off or restarted?
	2.	Are there any specific procedures or best practices to ensure that alarms trigger correctly on Android
	3. Is there a recommended way to handle this scenario, or is this a limitation of Android TV?

Any guidance or assistance would be greatly appreciated.

Thank you.

**Comment by chikoski** [comment]
Let me close this issue as it seems a question.
