### ISSUE TITLE
Variable Column Span on VerticalGridView

### ISSUE THREAD

**Issue by Glurt** [android/tv-samples#24]
I'm copying this from the previous repo as it was closed before an answer was provided.

I want to have a VerticalGridView with cards of different width. Something like this:

```
█ █ █ █
███ ███
█ █ █ █
█████ █
█ █ █ █
```

With regular support libraries, I'm able to use GridLayoutManager.SpanSizeLookup for this scenario.

Leanback seems to have it's own implementation of GridLayoutManager, but it it doesn't support the setSpanSizeLookup method, and even if it did, the manager is set and configured very early in the fragment, so just replacing it with another will cause issues, because it doesn't get configured as expected.

Is there any way to solve this and be able to specify how many columns should each element in the grid take?

**Comment by IanGClifton** [comment]
I don't believe there's an easy way to do this currently. A request for this feature exists at https://issuetracker.google.com/issues/138276997, so you could add details to that to help it get prioritized.

**Comment by nwhhades** [comment]
I want to add this feature request .I really need it

**Comment by nwhhades** [comment]
> I'm copying this from the previous repo as it was closed before an answer was provided.
> 
> I want to have a VerticalGridView with cards of different width. Something like this:
> 
> ```
> █ █ █ █
> ███ ███
> █ █ █ █
> █████ █
> █ █ █ █
> ```
> 
> With regular support libraries, I'm able to use GridLayoutManager.SpanSizeLookup for this scenario.
> 
> Leanback seems to have it's own implementation of GridLayoutManager, but it it doesn't support the setSpanSizeLookup method, and even if it did, the manager is set and configured very early in the fragment, so just replacing it with another will cause issues, because it doesn't get configured as expected.
> 
> Is there any way to solve this and be able to specify how many columns should each element in the grid take?

How do you solve the problem now？

**Comment by IanGClifton** [comment]
Closing to track in https://issuetracker.google.com/issues/138276997
