### ISSUE TITLE
Exoplayer Seekbar issue

### ISSUE THREAD

**Issue by Aravindraj93** [android/tv-samples#31]
How to make the exoplayer to play the video automatically instead of pressing enter or ok button in D-pad while forwarding the video using seekbar?

**Comment by dattahujare9** [comment]
I am also facing same issue.

**Comment by salehdeh76** [comment]
You could use this in ExoPlayerAdapter to play automatically  after seeking:
```

    private final Runnable mDelayedPlayAfterSeek = new Runnable() {
        @Override
        public void run() {
            mMediaPlayerGlue.playWhenPrepared();
        }
    };

    private final Handler mHandler = new Handler();

    @Override
    public void onPositionDiscontinuity() {
        mHandler.removeCallbacks(mDelayedPlayAfterSeek);
        mHandler.postDelayed(mDelayedPlayAfterSeek, 1000);
    }

```

**Comment by IanGClifton** [comment]
For questions with ExoPlayer itself, it's better to post on StackOverflow (https://stackoverflow.com/questions/tagged/exoplayer). In general, you can respond to a seek by implementing  onPositionDiscontinuity for Player.DISCONTINUITY_REASON_SEEK and trigger playback then.
