### ISSUE TITLE
[ClassicsKotlin] Media files return 404

### ISSUE THREAD

**Issue by xiaodao-google** [android/tv-samples#32]
Hi,

All the media files in media-feed.json of ClassicsKotlin returns 404, e.g.

https://android-tv-classics.firebaseapp.com/content/buffalo_dance/poster_art_buffalo_dance.jpg

This broke the sample app.

**Comment by xiaodao-google** [comment]
Hosting issue fixed.

**Comment by bcpeng** [comment]
Hi there, it seems like the hosting issue happens again.
