### ISSUE TITLE
Can't hide header

### ISSUE THREAD

**Issue by Tommy92708** [android/tv-samples#4]
When changing setHeadersState(HEADERS_ENABLED) to setHeadersState(HEADERS_DISABLED) on MainFragment.java, nothing is shown except for the logo and the search icon. I believed this is an issue w/ using the androidx.leanback library. Before migrating to use androidx leanback, the header can be disabled w/o affecting the main content. Any idea how to disable the header and still show the contents?

**Comment by owahltinez** [comment]
What sample are you referring to? If you think you have found an issue with the Leanback library, that should be filed in the AOSP issue tracker: https://issuetracker.google.com/components/192731

**Comment by IanGClifton** [comment]
Closing this issue out from no response. If you believe this is a bug in the Leanback library, please file it in the AOSP tracker as Oscar mentioned.
