### ISSUE TITLE
Custom HeadersFragment

### ISSUE THREAD

**Issue by maketvgithub** [android/tv-samples#40]
Hello,

I would like to know how can we customize HeadersFragment or make it look like YouTube or Google Play Music application?

For example in Google Play Music, when MainFragment is focused, HeadersFragment appears with icons only. I guess there is maybe some workaround because in HeadersFragment there is no such option to show icons only when MainFragment focused.

**Comment by IanGClifton** [comment]
Unfortunately we don't have the resources to offer 1:1 implementation support. StackOverflow (http://stackoverflow.com/questions/tagged/android-tv) is a better forum for these types of questions because you'll have a much larger audience to offer help.
