### ISSUE TITLE
How can I make the channel and programs visible to other apps?

### ISSUE THREAD

**Issue by ralf-wi** [android/tv-samples#43]
In `TvLauncherReceiver::onReceive()` the WorkManager is triggered to tell the channel and alls its programs to the "home screen".. 

According to documentation the onReceive is triggered after installation. I've set some logs output:
 - the onReceive is not triggered
 - but the WorkManagwer for ACTION_INITIALIZE_PROGRAMS in that onReceive() is triggered.
!?

I would like to make an app, which also can display these channels, like the home screen. Would that be possible? I would need the result of that WorkManager, made visible to another app!?

**Comment by IanGClifton** [comment]
That's not supported for 3rd party apps. Each individual app that gets triggered posts its channels and programs to the system's content provider. 3rd party apps cannot query that database for content provided by other apps.
