### ISSUE TITLE
TvLauncherReceiver::onReceive() is not triggered after install

### ISSUE THREAD

**Issue by ralf-wi** [android/tv-samples#44]
The documentation tells: 

> Make your default channel appear before your app is opened. You can make this behavior happen by adding a BroadcastReceiver that listens for the android.media.tv.action.INITIALIZE_PROGRAMS action, which the home screen sends after the app is installed

I've put a log cat on the TvLauncherReceiver::onReceive() just to sense when it is being triggered. But after a fresh installation, this log cat is never triggered.  But the default channel appears on the home screen

**Comment by IanGClifton** [comment]
The receiver is triggered if installed via the Play Store, not via ADB/Android Studio. If you want to manually trigger it, you can send the broadcast that the system sends with adb shell am broadcast -a android.media.tv.action.INITIALIZE_PROGRAMS -n com.android.tv.classics/.receivers.TvLauncherReceiver
