### ISSUE TITLE
How to customise VideoSupportFragment UI ?

### ISSUE THREAD

**Issue by KumarVelu** [android/tv-samples#49]
I want to add more components apart form player view, playback control and related videos that is shown in the demo. 
For example I want to add ImageView on top right corner of the screen, how do I customise the seekbar UI.

**Comment by IanGClifton** [comment]
Unfortunately we don't have the resources to offer 1:1 implementation support. StackOverflow (http://stackoverflow.com/questions/tagged/android-tv) is a better forum for these types of questions because you'll have a much larger audience to offer help.
