### ISSUE TITLE
The WebM video cannot be played

### ISSUE THREAD

**Issue by zmyqucai8** [android/tv-samples#54]
There was sound, but no image to show

**Comment by zmyqucai8** [comment]
ExoPlayer also has sound, no images

**Comment by zmyqucai8** [comment]
WebM videos under 720P can play, but are blurry
If the resolution is too high, the image will not be displayed

**Comment by zmyqucai8** [comment]
https://storage.opensea.io/files/029756e969c5307b0aa078807ffa6baa.webm
720P：https://storage.opensea.io/files/7c31b0392f828f110f6c0705c6b35df2.webm
1080P：https://storage.opensea.io/files/52fbe0d9951491049e0e2e31204f6f16.webm

**Comment by zmyqucai8** [comment]
Interestingly, some videos don't display images on Android TV 5.1, but they do on 7.1 (regardless of video resolution).

**Comment by IanGClifton** [comment]
This sounds like an issue with ExoPlayer rather than these specific samples. Please file at https://github.com/google/ExoPlayer/issues.
