### ISSUE TITLE
How to customize HeaderFragments

### ISSUE THREAD

**Issue by tyagi-bhoopesh** [android/tv-samples#56]
I would like to know how to customize the headers fragment if I want to create similar navigation slide menu for android tv app and also at top of header fragment screen, it should be profile icon and user name on it.

**Comment by IanGClifton** [comment]
Unfortunately we don't have the resources to offer 1:1 implementation support. StackOverflow (http://stackoverflow.com/questions/tagged/android-tv) is a better forum for these types of questions because you'll have a much larger audience to offer help.
