### ISSUE TITLE
change a text in lb_fullwidth_details_overview

### ISSUE THREAD

**Issue by a-sarollahi** [android/tv-samples#57]
can you please help me to know how can I change the text below the poster in leanback details view content?
I added this text to `lb_fullwidth_details_overview.xml` file but I couldn’t understand how can I change it!
thank you in advance.

![fNyvh](https://user-images.githubusercontent.com/71076488/120936104-6ef1be80-c706-11eb-9eaf-190a4fcf58ae.jpeg)

**Comment by IanGClifton** [comment]
See https://stackoverflow.com/questions/67804830/change-leanback-details-view-content-fragment
