### ISSUE TITLE
Error building LeanbackShowcase module.

### ISSUE THREAD

**Issue by KumarVelu** [android/tv-samples#59]
/.../AndroidTV/tv-samples/LeanbackShowcase/app/build/generated/ap_generated_sources/debug/out/androidx/leanback/leanbackshowcase/app/room/di/androidinject/LiveDataDetailViewWithVideoBackgroundFragmentModule_ContributeLiveDataDetailViewWithVideoBackgroundFragment.java:26: error: incompatible types: Class<LiveDataDetailViewWithVideoBackgroundFragment> cannot be converted to Class<? extends Fragment>
  @FragmentKey(LiveDataDetailViewWithVideoBackgroundFragment.class)
                                                            ^
/.../AndroidTV/tv-samples/LeanbackShowcase/app/build/generated/ap_generated_sources/debug/out/androidx/leanback/leanbackshowcase/app/room/di/androidinject/SearchFragmentInjectorInstallmentFactoryBindingModule_ContributeSearchFragment.java:24: error: incompatible types: Class<SearchFragment> cannot be converted to Class<? extends Fragment>
  @FragmentKey(SearchFragment.class)
                             ^
/.../AndroidTV/tv-samples/LeanbackShowcase/app/build/generated/ap_generated_sources/debug/out/androidx/leanback/leanbackshowcase/app/room/di/androidinject/LiveDataFragmentModule_ContributeLiveDataFragment.java:23: error: incompatible types: Class<LiveDataFragment> cannot be converted to Class<? extends Fragment>
  @FragmentKey(LiveDataFragment.class)
                               ^
/.../AndroidTV/tv-samples/LeanbackShowcase/app/src/main/java/androidx/leanback/leanbackshowcase/app/room/di/androidinject/AppComponent.java:34: error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentProcessor was unable to process this interface because not all of its dependencies could be resolved. Check for compilation errors or a circular dependency with generated code.
public interface AppComponent {

**Comment by IanGClifton** [comment]
It looks like Android Studio fails with `Unable to load class 'javax.xml.bind.JAXBException'.` when I try to build. Updating the gradle version causes me to see the same errors as above. The version of dagger used in the sample is really old and there are a bunch of changes throughout to update to the latest version, so this may need some additional investigation.

**Comment by IanGClifton** [comment]
Looks like this is working now. I filed #61 separately for digging into the Dagger issues with LiveDataRowsActivity.
