### ISSUE TITLE
scrollToPosition does not work without adding the padding to focus view

### ISSUE THREAD

**Issue by pawan52tiwari** [android/tv-samples#62]
Hi All,
I am using the lenabck grid with for TV app. I have nested Horizontalgird view inside Vertical GridView.

When scroll happens and next card gets focus i am calling the scrollToPosition based on scroll direction either on Horizontalgird or verticalgrid to show a constant scroll.

Scrolling works fine if i add padding to the the focus view

 ```
view.setOnFocusChangeListener(new View.OnFocusChangeListener() {
            @Override
            public void onFocusChange(View v, boolean hasFocus) {
                if(hasFocus){
                   v.setPadding(1,0,0,0);
                    TitleCardViewHolder.this.carouselItemAdapter.scrollToPosition(getLayoutPosition());
                }else {
                    v.setPadding(0,0,0,0);
                }
            }
        });**
```**


If i remove the line     v.setPadding(1,0,0,0); then scrollToPosition does not work at all


Why it is required to add padding to make scrollToPosition work

**Comment by IanGClifton** [comment]
This sounds like a bug with the Leanback SDK, which you can file via https://issuetracker.google.com/components/460758.
