### ISSUE TITLE
Vertical letterboxing when displayed on TVs

### ISSUE THREAD

**Issue by OmidID** [android/tv-samples#65]
Hello,

I designed my app following all the rules from documentation and also I took examples from here, but Google Console keeps rejecting my app and I don't have enough details. Maybe you have any idea how can I know what is the problem or how to solve it?

> Not designed in landscape orientation
> Your app or game has vertical letterboxing when displayed on TVs. Please design your TV app or game to be displayed in landscape mode. Please refer to our [TV Layouts documentation](https://developer.android.com/training/tv/start/layouts.html#structure) for more details.

All the pages are force to be landscape and I used AndroidX Leanback library

[This is my app url](https://play.google.com/store/apps/details?id=com.toranux.tv.manoto)

I really need help or any suggestion, please. I have had this problem for more than 5 months.

Thanks in advance.

**Comment by IanGClifton** [comment]
Unfortunately the review team is separate from the team that manages these samples, but if you're using the leanback library for all screens and the orientation for every activity is set to landscape in your manifest, then the most likely problem is video that isn't in 16:9 format (e.g., a 3:2 video will have vertical letterboxing). I don't know the details of the review process but maybe a content format warning or a zoom to fit would help?

**Comment by OmidID** [comment]
That's a good idea. I didn't think about this particular case. And I'll try it. 

And Yeh, For sure I know the review team is separate. But as resources for Android TV development is so limited on the internet I thought that maybe someone here can figure out what is the problem. 

@IanGClifton  Thank you so much :)
