### ISSUE TITLE
Crash exoPlayer for big videos 3 hours

### ISSUE THREAD

**Issue by Allan-Nava** [android/tv-samples#66]

**Comment by IanGClifton** [comment]
If the issue is specific to ExoPlayer and not one of the samples in this repo, please file it at https://github.com/google/ExoPlayer/issues and include a stacktrace, so that team can help debug it.

**Comment by Allan-Nava** [comment]
> If the issue is specific to ExoPlayer and not one of the samples in this repo, please file it at https://github.com/google/ExoPlayer/issues and include a stacktrace, so that team can help debug it.

Ok thanks, the videos are HLS
