### ISSUE TITLE
Media keys don't work

### ISSUE THREAD

**Issue by gordonjb** [android/tv-samples#9]
Hope this isn't a stupid issue but:

I'm under the impression that media keys functionality are automatic with leanback, however I've been having issues with it in my own project and also with the Leanback project.

When running the Leanback project in an emulator and on real hardware, I've noticed that the play/pause buttons function but others don't (at least the fast forward and rewind buttons on both, i've also tried the stop button on real hardware and that also does nothing)

Is this wrong, or is support not included automatically and I'm missing some implementation step

**Comment by IanGClifton** [comment]
The recommended way of handling the buttons is with MediaSession, which the Leanback example doesn't demonstrate. If you use MediaSession, you can have all the media buttons treated as callbacks (ideally, you also do the same with the transport control UI as well). Some common video players will do a lot of this for you though. For example, if you use ExoPlayer, you can use MediaSessionConnector (https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.html) to call the applicable player methods. That is demonstrated in the ClassicKotlins project. If you want/need to more directly handle the media session, you can also do that (see the MusicPlaybackService in LeanbackShowcase).
